### ISSUE TITLE
Mobile issue on pro.homeowner.ai

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/pro.homeowner.ai#1]
@codextiny 

Mobile issue on [pro.homeowner.ai](https://pro.homeowner.ai/) 

1. Menu not working on home page (no hover state)
2. Stratus showing up on [https://homeowner.ai/about-us/](url) mobile view 
![image](https://github.com/user-attachments/assets/c0e95326-0eb3-4610-8266-86353d396c22); this page does not exist on homeowner.ai but when someone googles "homeowner.ai about us" this shows up. 

Access:
support@milestones.ai
M!l3st0nesL@bs

**Comment by codextiny** [comment]
@shannonbaldwin 

This page actually exists in pages listing, and its published, you can unpublished it and as per header concerned you need to clone the home page and update content according to about us page the it will work fine.

![image](https://github.com/user-attachments/assets/09802b83-75ea-4c10-acd3-bf50d276a731)

**Comment by shannonbaldwin** [comment]
@codextiny Thank you. Can you please look into why pro.homeowner.ai is not working in mobile?

**Comment by shannonbaldwin** [comment]
@codextiny When I try to update the logo on homeowner.ai home page, I am getting this error.

![image](https://github.com/user-attachments/assets/14f9e8fa-343b-41fd-8f60-27431e1f16b2)

**Comment by shannonbaldwin** [comment]
@codextiny This is also now showing up. There seems to be an issue on pro.homeowner.ai website. 
<img width="385" alt="image" src="https://github.com/user-attachments/assets/2471c731-594f-4675-875f-1b86902f08d3">

**Comment by codextiny** [comment]
@shannonbaldwin 

https://elementor.com/help/how-to-fix-the-preview-could-not-be-loaded-error/?utm_source=editor-panel&utm_medium=wp-dash&utm_campaign=learn#permissions

its something happened with your theme, i guess some files are missing, you should contact to theme support..
![image](https://github.com/user-attachments/assets/a921c9ba-00bd-4faf-8ae6-eebb16a25127)

they recently updated their theme, it might be possible some files or functionality missing after recent update ..

Thanks

**Comment by codextiny** [comment]
> @codextiny When I try to update the logo on homeowner.ai home page, I am getting this error.
> 
> ![image](https://private-user-images.githubusercontent.com/167017886/372179812-14f9e8fa-343b-41fd-8f60-27431e1f16b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MDk0NzIsIm5iZiI6MTcyNzgwOTE3MiwicGF0aCI6Ii8xNjcwMTc4ODYvMzcyMTc5ODEyLTE0ZjllOGZhLTM0M2ItNDFmZC04ZjYwLTI3NDMxZTFmMTZiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxODU5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzRiOWZiNjMyMGE5YzBiNzU3YzU1NDE1ODQ3ZTgwM2I3ODkwM2Q3MTBlNmMwNmQyYTNiMDIxMDIzOTcyZGQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1yFK0V_OZ-zwxXPhTFR8H_Egm72MxiTuhx40KHmjfII)

This issue is fixed now, please check.

Before, you have used "Day and name" permalink structure and those are not working, if you need this then you should talk to theme support.
![image](https://github.com/user-attachments/assets/123760ee-aa84-430d-a74f-4d3b1799628b)

After, now we selected plain permalink, and your url's working fine.
![image](https://github.com/user-attachments/assets/f1f12ccc-9b28-48a1-a5a8-28b3d17949b6)

Thanks

**Comment by codextiny** [comment]
> @codextiny This is also now showing up. There seems to be an issue on pro.homeowner.ai website. <img alt="image" width="385" src="https://private-user-images.githubusercontent.com/167017886/372271170-2471c731-594f-4675-875f-1b86902f08d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MDk0NzIsIm5iZiI6MTcyNzgwOTE3MiwicGF0aCI6Ii8xNjcwMTc4ODYvMzcyMjcxMTcwLTI0NzFjNzMxLTU5NGYtNDY3NS04NzVmLTFiODY5MDJmMDhkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxODU5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDU4MmFkMGRkOTk4NzM5MTBkNDk5MzQyZmY4NTM0Y2JjZWY1MzU2MjI0OWVlZTgwYzEwMTE4ZmMwYzBmZDY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.x44yMmL-tY2-LUEeaAWQqvl89_1jNSu8J2gOyaKhRo8">

pro.homeowner.ai is working fine for us, can you please send exact url which shows stratus content ..

Thanks .

**Comment by codextiny** [comment]
@shannonbaldwin 

pro.homeowner.ai menu is not working like homeowner.ai, we have checked possible option but its still not working, if you need to confirm with theme support team, please contact otherwise we have custom code solution like we did before for homeowner.ai and its time taking because pro.homeowner.ai menu have submenus as well .

Also please provide links where stratus stuff showing on mobile .??

Thanks .

**Comment by codextiny** [comment]
@shannonbaldwin 

pro.homeowner.ai menu is not working like homeowner.ai, we have checked possible option but its still not working, if you need to confirm with theme support team, please contact otherwise we have custom code solution like we did before for homeowner.ai and its time taking because pro.homeowner.ai menu have submenus as well .

Thanks .

**Comment by shannonbaldwin** [comment]
@codextiny Please use custom code solution like you did for homeowner.ai. I think the Stratus issue is because of mobile not working. Let's try that first.

**Comment by codextiny** [comment]
@shannonbaldwin 

Menu is done from our side, please check

Thanks
